### ISSUE TITLE
DynamicTool throws an error if there is a curly bracket in the tool description

### ISSUE THREAD

**Issue by Qarj** [hwchase17/langchainjs#1114]
If you create a DynamicTool with a curly bracket character, it will crash. The error hints at the tool description being parsed in some special way, but I didn't find documentation on this. This is all I found: https://js.langchain.com/docs/modules/agents/tools/

Here is some code demonstrating the issue:

```js
import * as dotenv from 'dotenv';
dotenv.config();

import { ChatOpenAI } from 'langchain/chat_models/openai';
import { initializeAgentExecutorWithOptions } from 'langchain/agents';
import { DynamicTool } from 'langchain/tools';

let iteration = 0;

async function jobSearch(query) {
    console.log('jobSearch input:', query);
    return 'Search results: job1, job2, job3';
}

const callbacks = [
    {
        handleLLMStart: async (llm, prompts) => {
            iteration++;
            console.log(`${iteration} LLMStart, llm`, llm);
            console.log(`${iteration} LLMStart, prompts`, prompts);
        },
        handleLLMEnd: async (output) => {
            console.log(`${iteration} LLMEnd, output`, output);
        },
        handleLLMError: async (err) => {
            log.error(`${iteration} LLMError, err`, err);
        },
    },
];

export const run = async () => {
    const model = new ChatOpenAI({ temperature: 0, verbose: false, callbacks, modelName: 'gpt-4' });
    const tools = [
        new DynamicTool({
            name: 'jobSearch',
            description: `Useful for finding jobs. The input to this tool is JSON containing { location, jobTitle, salary } and the the output will be a list of jobs that match the query.`,
            func: async (query) => {
                return await jobSearch(query);
            },
        }),
    ];

    const executor = await initializeAgentExecutorWithOptions(tools, model, {
        agentType: 'chat-zero-shot-react-description',
    });

    const input = `Search me test engineer jobs in London`;

    console.log(`Executing with input "${input}"...`);

    const result = await executor.call({ input });

    console.log(`Final answer after ${iteration} iterations:\n`);
    console.log(result.output);
};

run();
```

Gives output

```txt
Executing with input "Search me test engineer jobs in London"...
file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/prompts/chat.js:178
                    throw new Error(`Missing value for input variable \`${inputVariable}\``);
                          ^

Error: Missing value for input variable ` location, jobTitle, salary `
    at file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/prompts/chat.js:178:27
    at Array.reduce (<anonymous>)
    at ChatPromptTemplate.formatMessages (file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/prompts/chat.js:176:62)
    at async ChatPromptTemplate.formatPromptValue (file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/prompts/chat.js:74:32)
    at async LLMChain._call (file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/chains/llm_chain.js:79:29)
    at async LLMChain.call (file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/chains/base.js:65:28)
    at async LLMChain.predict (file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/chains/llm_chain.js:98:24)
    at async ChatAgent._plan (file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/agents/agent.js:197:24)
    at async AgentExecutor._call (file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/agents/executor.js:82:28)
    at async AgentExecutor.call (file:///Users/tim.buckland/git/scrapbook/node/langchain/node_modules/langchain/dist/chains/base.js:65:28)

Node.js v18.16.0
```

Using langchain `0.0.68`

If you remove the curly brackets from the description, the code will run, but still not work correctly. Will raise a separate issue for that.

**Comment by vialcollet** [comment]
This is similar to this issue: #1082 
We need to be able to escape curly braces.

**Comment by Qarj** [comment]
Hi @dosu-beta I looked at the code and worked out you can escape a curly brace by adding another curly brace like this `{{` so you can close the issue. Best regards!
