### ISSUE TITLE
MessagesPlaceholder generates an error

### ISSUE THREAD

**Issue by vialcollet** [hwchase17/langchainjs#1143]
I have a weird error when using `BufferMemory` and `MessagesPlaceholder`.

It is complaining about `m._getType is not a function`.

It only happens if I have this option in my template: new `MessagesPlaceholder('history'),`. When I remove it, everything works fine (but without memory obviously)...

This issue has been confirmed by 2 other developpers on discord

Here is my api endpoint:

```ts
// imports

export const POST: RequestHandler = async ({ request }) => {
    
    // Auth block
    
    // Parse request
    
    console.log(history);
    // [
    //     { role: 'system', text: 'You are Sonia, a helpful assistant.' },
    //     { role: 'human', text: 'My name is Bastien.' },
    //     { role: 'ai', text: 'Nice to meet you, Bastien.' },
    //     { role: 'human', text: 'What is my name?' }
    // ]

    console.log(query);
    // What is my name?
    
    const lcChatMessageHistory = new ChatMessageHistory(history);
    
    console.log(lcChatMessageHistory);
    // ChatMessageHistory {
    //     messages: [
    //       { role: 'system', text: 'You are Sonia, a helpful assistant.' },
    //       { role: 'human', text: 'My name is Bastien.' },
    //       { role: 'ai', text: 'Nice to meet you, Bastien.' },
    //       { role: 'human', text: 'Who am I?' },
    //     ]
    //   }

    const memory = new BufferMemory({
        chatHistory: lcChatMessageHistory,
        returnMessages: true,
        memoryKey: 'history'
    });

    const chat = new ChatOpenAI({ 
        temperature: temperature, 
        openAIApiKey: OPENAI_API_KEY 
    });

    const chatPrompt = ChatPromptTemplate.fromPromptMessages([
        SystemMessagePromptTemplate.fromTemplate(
            'The following is a friendly conversation between a human and an AI.'
        ),
        new MessagesPlaceholder('history'),
        HumanMessagePromptTemplate.fromTemplate('{input}')
    ]);

    const chain = new ConversationChain({
        memory: memory,
        llm: chat,
        prompt: chatPrompt
    });

    const response = await chain.call({
        input: query
    });

    console.log(JSON.stringify(response));

    return new Response(JSON.stringify(response), {
        headers: {
            'Content-Type': 'application.json'
        }
    });
};
```

And here is the error I'm getting:

```shell
TypeError: m._getType is not a function
    at getBufferString (file:///home/bastien/apps/skeleton-app/node_modules/.pnpm/langchain@0.0.66/node_modules/langchain/dist/memory/base.js:26:15)
    at file:///home/bastien/apps/skeleton-app/node_modules/.pnpm/langchain@0.0.66/node_modules/langchain/dist/chat_models/base.js:12:62
    at Array.map (<anonymous>)
    at ChatOpenAI.generate (file:///home/bastien/apps/skeleton-app/node_modules/.pnpm/langchain@0.0.66/node_modules/langchain/dist/chat_models/base.js:12:41)
    at ChatOpenAI.generatePrompt (file:///home/bastien/apps/skeleton-app/node_modules/.pnpm/langchain@0.0.66/node_modules/langchain/dist/chat_models/base.js:46:21)
    at ConversationChain._call (file:///home/bastien/apps/skeleton-app/node_modules/.pnpm/langchain@0.0.66/node_modules/langchain/dist/chains/llm_chain.js:80:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConversationChain.call (file:///home/bastien/apps/skeleton-app/node_modules/.pnpm/langchain@0.0.66/node_modules/langchain/dist/chains/base.js:65:28)
    at async POST (/src/routes/api/chat/+server.ts:46:20)
    at async Module.render_endpoint (/node_modules/.pnpm/@sveltejs+kit@1.15.10_svelte@3.58.0_vite@4.3.4/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:47:20)
```

**Comment by nfcampos** [comment]
Hi,

When you instantiate `ChatMessageHistory` it expects an array of instances of BaseChatMessage or subclasses, not an array of plain objects as you have there. You can do that eg. like this

```
interface StoredMessage {
  role: string;
  text: string;
}

function mapStoredMessagesToChatMessages(
  messages: StoredMessage[]
): BaseChatMessage[] {
  return messages.map((message) => {
    switch (message.role) {
      case "human":
        return new HumanChatMessage(message.text);
      case "ai":
        return new AIChatMessage(message.text);
      case "system":
        return new SystemChatMessage(message.text);
      default:
        throw new Error("Role must be defined for generic messages");
    }
  });
}

const lcChatMessageHistory = new ChatMessageHistory(mapStoredMessagesToChatMessages(history));
```

**Comment by vialcollet** [comment]
Yes perfect, thanks.
