### ISSUE TITLE
[Urgent] 400 Error in Chroma.fromDocument

### ISSUE THREAD

**Issue by ruai0511** [hwchase17/langchainjs#1231]
I'd like to integrate langchain js and chroma, but I always get the 400 error in this line: 
```javascript
const vectorStore = await Chroma.fromDocuments(       
  docs,      
  new OpenAIEmbeddings({ openAIApiKey: "sk-xxx"}),       
  { collectionName: "state_of_the_union" }     
); 
``` 
Here's the traceback:
```
error Error: Request failed with status code 400
at createError (/Users/ruai/Desktop/interview/node_modules/chromadb/node_modules/axios/lib/core/createError.js:16:15)     
at settle (/Users/ruai/Desktop/interview/node_modules/chromadb/node_modules/axios/lib/core/settle.js:17:12)     
at IncomingMessage.handleStreamEnd (/Users/ruai/Desktop/interview/node_modules/chromadb/node_modules/axios/lib/adapters/http.js:322:11)     
at IncomingMessage.emit (node:events:525:35)     
at endReadableNT (node:internal/streams/readable:1359:12)     
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
{   digest: undefined}
``` 

From the traceback, it seems that the fromDocuments function is doing a http request but encounters some axios error (not sure about this). 

The only change I made from the official example is adding the  { openAIApiKey: "sk-xxx"} inside the OpenAIEmbeddings constructor. If I don't add it, it'll give the error that there's no api key. I'm not sure what's going on. And I have a really tight schedule to finish this.. Thank you!

**Comment by VictorRodas99** [comment]
Any solution for this? I have the same error..

**Comment by jacoblee93** [comment]
This may be fixed by https://github.com/hwchase17/langchainjs/pull/1348

**Comment by isSerge** [comment]
I am having the same issue with `chromadb 1.5.2`

**Comment by joaomantovani** [comment]
Facing the same issue with pinecone
