### ISSUE TITLE
Bug: ChatMessagePromptTemplate not working: ‘Unknown message type: generic’

### ISSUE THREAD

**Issue by jhakeinson** [hwchase17/langchainjs#1344]
When using Langchain’s ChatMessagePromptTemplate, I encountered an error that says ‘Unknown message type: generic’. I’m not sure what’s causing this error or how to resolve it. Can you help me figure out what’s going on and how to fix it?

Here's my code snippet:
```
async getChatResponse(message: string): Promise<ChainValues> {
    const chatOpenAI = new ChatOpenAI({
      openAIApiKey: this.configService.get<string>('OPENAI_API_KEY'),
      modelName: 'gpt-3.5-turbo',
      temperature: 1,
      maxTokens: 200,
    });

    const prompts = ChatPromptTemplate.fromPromptMessages([
      ChatMessagePromptTemplate.fromTemplate(
        'You are a comedian who always responds to anything with a joke.',
        'system',
      ),
      ChatMessagePromptTemplate.fromTemplate('{message}', 'human'),
    ]);

    const chain = new LLMChain({
      llm: chatOpenAI,
      prompt: prompts,
      verbose: true,
    });

    const response = await chain.call({
      message: message,
    });

    return response;
  }
```

And here is the verbose output:
```
[chain/start] [1:chain:llm_chain] Entering Chain run with input: {
api:dev:   "message": "Hi! I'm Joe Biden.",
api:dev:   "history": []
api:dev: }
api:dev: [llm/start] [1:chain:llm_chain > 2:llm:openai] Entering LLM run with input: {
api:dev:   "messages": [
api:dev:     [
api:dev:       {
api:dev:         "_type": "generic",
api:dev:         "content": "You are a comedian who always responds to anything with a joke."
api:dev:       },
api:dev:       {
api:dev:         "_type": "generic",
api:dev:         "content": "Hi! I'm Joe Biden."
api:dev:       }
api:dev:     ]
api:dev:   ]
api:dev: }
api:dev: [llm/error] [1:chain:llm_chain > 2:llm:openai] [1ms] LLM run errored with error: "Unknown message type: generic"
api:dev: [chain/error] [1:chain:llm_chain] [2ms] Chain run errored with error: "Unknown message type: generic"
api:dev: [Nest] 5326  - 05/20/2023, 11:46:04 PM   ERROR [ExceptionsHandler] Unknown message type: generic
api:dev: Error: Unknown message type: generic
api:dev:     at messageTypeToOpenAIRole (/home/jhake/coding/personal/messenger-chatbot-proj/node_modules/.pnpm/langchain@0.0.75/node_modules/langchain/dist/chat_models/openai.cjs:22:19)
api:dev:     at /home/jhake/coding/personal/messenger-chatbot-proj/node_modules/.pnpm/langchain@0.0.75/node_modules/langchain/dist/chat_models/openai.cjs:273:19
api:dev:     at Array.map (<anonymous>)
api:dev:     at ChatOpenAI._generate (/home/jhake/coding/personal/messenger-chatbot-proj/node_modules/.pnpm/langchain@0.0.75/node_modules/langchain/dist/chat_models/openai.cjs:272:41)
api:dev:     at /home/jhake/coding/personal/messenger-chatbot-proj/node_modules/.pnpm/langchain@0.0.75/node_modules/langchain/dist/chat_models/base.cjs:30:82
api:dev:     at Array.map (<anonymous>)
api:dev:     at ChatOpenAI.generate (/home/jhake/coding/personal/messenger-chatbot-proj/node_modules/.pnpm/langchain@0.0.75/node_modules/langchain/dist/chat_models/base.cjs:30:56)
api:dev:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:     at LLMChain._call (/home/jhake/coding/personal/messenger-chatbot-proj/node_modules/.pnpm/langchain@0.0.75/node_modules/langchain/dist/chains/llm_chain.cjs:95:33)
api:dev:     at LLMChain.call (/home/jhake/coding/personal/messenger-chatbot-proj/node_modules/.pnpm/langchain@0.0.75/node_modules/langchain/dist/chains/base.cjs:68:28)
```

It seems that `_type` is not getting the value set on `ChatMessagePromptTemplate.role`.

Is this by design or am I doing something wrong?

**Comment by jacoblee93** [comment]
`fromPromptMessages` expects an array of ChatMessages, not prompt templates, as input. Try:
```
    import {
        SystemChatMessage,
        HumanChatMessage, 
    } from "langchain/schema";
    const prompts = ChatPromptTemplate.fromPromptMessages([
      new SystemChatMessage(
        'You are a comedian who always responds to anything with a joke.',
      ),
      new HumanChatMessage('{message}')
    ]);
```
