### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by conroywhitney** [hwchase17/langchainjs#159]
Hey! Thanks for your work on this project. It's so exciting 🤩 

I'm using this lib inside https://github.com/sullivan-sean/chat-langchainjs and got the following error when importing docs:

```
ReferenceError: Headers is not defined
    at null.createRequest (./chat-langchainjs/node_modules/langchain/src/util/axios-fetch-adapter.js:96:19)
    at null.fetchAdapter (./chat-langchainjs/node_modules/langchain/src/util/axios-fetch-adapter.js:20:19)
    at null.dispatchRequest (./chat-langchainjs/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (./chat-langchainjs/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap (./chat-langchainjs/node_modules/axios/lib/helpers/bind.js:9:15)
    at null.<anonymous> (./chat-langchainjs/node_modules/openai/dist/common.js:147:22)
    at null.<anonymous> (./chat-langchainjs/node_modules/openai/dist/api.js:1539:123)
```

Where is the `Headers` definition supposed to come from?

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/util/axios-fetch-adapter.js#L102

From here?

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/agents/tools/requests.ts#L3

**Comment by conroywhitney** [comment]
Pinging @nfcampos since you recently worked on https://github.com/hwchase17/langchainjs/pull/118 🙏

**Comment by nfcampos** [comment]
Hi @conroywhitney 
`Headers` is meant to be in global scope with `fetch`. Can you confirm the version of Node you're running this on? See these new instructions here for running it in Node 16 https://hwchase17.github.io/langchainjs/docs/getting-started#installation
Does that fix it?

**Comment by conroywhitney** [comment]
Thanks -- you're totally right. I was on Node 16, so this fixed it:

```
NODE_OPTIONS='--experimental-fetch' yarn ingest
```
