### ISSUE TITLE
Can't use AbortSignal and Memory at the same time

### ISSUE THREAD

**Issue by CainYc** [hwchase17/langchainjs#1610]
I try to coding like this
```
const memory: BufferWindowMemory = this.getBufferMemory(reqUser.id);
const chatPrompt = ChatPromptTemplate.fromPromptMessages([
  SystemMessagePromptTemplate.fromTemplate(role.detail + '{text}'),
]);
const chain = new ConversationChain({
      llm: this.chatStreamModel,
      prompt: chatPrompt,
      memory: memory,
    });
...
res = await chain.call({ text: question, signal: cancel.signal }, [
  {
    handleLLMStart(llm: any, prompts: string[]) {
      console.log(JSON.stringify(prompts));
    },
    handleLLMNewToken(token: string) {
      if (roleId === 2 && token.endsWith('\n')) {
        emitter.emit(user.userId, '');
      }
      emitter.emit(user.userId, token);
    },
    handleChainEnd(res: ChainValues): Promise<void> | void {
      that.saveCostLog(question, roleId, res, reqUser).then(() => {
        console.log('save cost log success');
      });
    },
  },
]);
```
but i get error 
```
input values have 2 keys, you must specify an input key or pass only 1 key as input
at getInputValue (/home/***/node_modules/langchain/dist/memory/base.cjs:20:11)
at BufferWindowMemory.saveContext (/home/***/node_modules/langchain/dist/memory/chat_memory.cjs:40:75)
at ConversationChain.call (/home/***/node_modules/langchain/dist/chains/base.cjs:75:31)
```
if i change
`res = await chain.call({ text: question, signal: cancel.signal }, [`
to
`res = await chain.call({ text: question }, [`
the code run be fine.

I think is **memory.saveContext** have some prompt check, but i have no time to read code.
Please help me.

**Comment by CainYc** [comment]
I read the code and find the solution.
In file 
[**langchain/src/chains/llm_chain.ts** line 106](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chains/llm_chain.ts#LL106C1-L106C1)
```
const valuesForPrompt = { ...values };
const valuesForLLM: this["llm"]["CallOptions"] = {};
for (const key of this.llm.callKeys) {
  if (key in values) {
    valuesForLLM[key as keyof this["llm"]["CallOptions"]] = values[key];
    delete valuesForPrompt[key];
  }
}
```
In chain.call(), their delete the "CallOptions" for get final output.
In Memory.SaveContext(), the check the input values, but not delete the "CallOptions".
Code in [**langchain/src/memory/base.ts**](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/memory/base.ts#L26)
```
export const getInputValue = (inputValues: InputValues, inputKey?: string) => {
  if (inputKey !== undefined) {
    return inputValues[inputKey];
  }
  const keys = Object.keys(inputValues);
  if (keys.length === 1) {
    return inputValues[keys[0]];
  }
  throw new Error(
    `input values have ${keys.length} keys, you must specify an input key or pass only 1 key as input`
  );
};
```
And the solution is in this code.
```
if (inputKey !== undefined) {
  return inputValues[inputKey];
}
```
If we want use memory and cancle signal or timeout same time, we need set **inputKey** when we create a Memory instance, like this.
```
new BufferWindowMemory({
      k: this.configService.get('HISTORY_SIZE'),
      memoryKey: 'history',
      inputKey: 'text',
      returnMessages: true,
      chatHistory: new RedisChatMessageHistory({
        sessionId: sessionId,
        config: {
          url: this.configService.get('REDIS_HOST'),
        },
      }),
    });
```
I think this exemple need add to Langchain JS/TS Docs.
