### ISSUE TITLE
Azure openai issue

### ISSUE THREAD

**Issue by shanurrahman** [hwchase17/langchainjs#1750]
I have attempted using various classes such as 'PromptLayerOpenAI' and 'ChatOpenAI' to instantiate OpenAIChat, but they have all returned the same error.
tried with `"langchain": "0.0.82"` and the latest 0.92 version.

I noticed that it keeps calling the embeddings api instead of chat completion one! The correct endpoint should've been
https://shanurrahman.openai.azure.com/openai/deployments/fahm/chat/completions?api-version=2023-03-15-preview

```ts
return new OpenAIChat({
      temperature: 0.9,
      azureOpenAIApiKey: process.env.AZURE_OPENAI_API_KEY,
      azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME,
      azureOpenAIApiDeploymentName: 'fahm',
      azureOpenAIApiVersion: process.env.AZURE_OPENAI_API_VERSION,
      modelName: 'gpt-3.5',
    });
    
  ```
  Error 
  ---  
```
 at settle (/Users/shanurrahman/Documents/Gitlab/yc/fahm/frontend/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/shanurrahman/Documents/Gitlab/yc/fahm/frontend/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.3.0',
      Authorization: 'Bearer ',
      'api-key': '',
      'Content-Length': 69
    },
    method: 'post',
    params: { 'api-version': '2023-03-15-preview' },
    data: '{"model":"text-embedding-ada-002","input":"who is this book about ?"}',
    url: 'https://some.openai.azure.com/openai/deployments/fahm/embeddings'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 69,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'some.openai.azure.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'some.openai.azure.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 134041,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /openai/deployments/fahm/embeddings?api-version=2023-03-15-preview HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: OpenAI/NodeJS/3.3.0\r\n' +
      'Authorization: Bearer token\r\n' +
      'api-key: \r\n' +
      'Content-Length: 69\r\n' +
      'Host: some.openai.azure.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/openai/deployments/fahm/embeddings?api-version=2023-03-15-preview',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://some.openai.azure.com/openai/deployments/fahm/embeddings?api-version=2023-03-15-preview',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 18,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'some.openai.azure.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 69,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://some.openai.azure.com/openai/deployments/fahm/embeddings?api-version=2023-03-15-preview',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kEndCalled)]: true,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      authorization: [Array],
      'api-key': [Array],
      'content-length': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      'content-length': '303',
      'content-type': 'application/json',
      'openai-processing-ms': '5.8251',
      'apim-request-id': 'fd9789c3-612f-46f7-b20c-284bb698237a',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'x-content-type-options': 'nosniff',
      'x-ms-region': 'East US',
      date: 'Fri, 23 Jun 2023 21:17:45 GMT',
      connection: 'close'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      params: [Object],
      data: '{"model":"text-embedding-ada-002","input":"who is this book about ?"}',
      url: 'https://some.openai.azure.com/openai/deployments/fahm/embeddings'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 69,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /openai/deployments/fahm/embeddings?api-version=2023-03-15-preview HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: OpenAI/NodeJS/3.3.0\r\n' +
        'Authorization: Bearer token\r\n' +
        'api-key: \r\n' +
        'Content-Length: 69\r\n' +
        'Host: some.openai.azure.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/openai/deployments/fahm/embeddings?api-version=2023-03-15-preview',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'some.openai.azure.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  attemptNumber: 1,
  retriesLeft: 6
}
```

**Comment by khanguslee** [comment]
I am using this instead for Azure Open AI:

```ts
import { OpenAI } from "langchain/llms/openai";
import { ChatOpenAI } from "langchain/chat_models/openai";

const config = {
  temperature: 0.9,
  modelName: process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME,
  azureOpenAIApiKey: process.env.OPENAI_API_KEY, // In Node.js defaults to process.env.AZURE_OPENAI_API_KEY
  azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME, // In Node.js defaults to process.env.AZURE_OPENAI_API_INSTANCE_NAME
  azureOpenAIApiDeploymentName: process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME, // In Node.js defaults to process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME
  azureOpenAIApiVersion: process.env.OPENAI_API_VERSION, // In Node.js defaults to process.env.AZURE_OPENAI_API_VERSION
};

// Create model to be reused
const MODEL = new ChatOpenAI(config);
const LLM_MODEL = new OpenAI(config);
```

Maybe try `ChatOpenAI` instead to see if it works for you.

**Comment by lz82** [comment]
> I am using this instead for Azure Open AI:
> 
> ```ts
> import { OpenAI } from "langchain/llms/openai";
> import { ChatOpenAI } from "langchain/chat_models/openai";
> 
> const config = {
>   temperature: 0.9,
>   modelName: process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME,
>   azureOpenAIApiKey: process.env.OPENAI_API_KEY, // In Node.js defaults to process.env.AZURE_OPENAI_API_KEY
>   azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME, // In Node.js defaults to process.env.AZURE_OPENAI_API_INSTANCE_NAME
>   azureOpenAIApiDeploymentName: process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME, // In Node.js defaults to process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME
>   azureOpenAIApiVersion: process.env.OPENAI_API_VERSION, // In Node.js defaults to process.env.AZURE_OPENAI_API_VERSION
> };
> 
> // Create model to be reused
> const MODEL = new ChatOpenAI(config);
> const LLM_MODEL = new OpenAI(config);
> ```
> 
> Maybe try `ChatOpenAI` instead to see if it works for you.

I had the same issue, tried ChatOpenAI and still has the same issue 

<img width="489" alt="image" src="https://github.com/hwchase17/langchainjs/assets/39956694/35a6116d-fb5f-4cc1-a2d2-6118baf3366e">
<img width="565" alt="image" src="https://github.com/hwchase17/langchainjs/assets/39956694/7c1929e2-e9a8-4556-b7da-49c97a2ac5da">

**Comment by shanurrahman** [comment]
any update on this ?

**Comment by Eventidus** [comment]
The reason for the error is a 400 bad request. You need to check your code, especially the part where you are passing problematic parameters.

**Comment by santiagocalvoazumo** [comment]
try using gpt-35-turbo for modelName instead, I remember having that work on a difrent issue

**Comment by shanurrahman** [comment]
Tried everything, and still can't get it to work! 
The code can be found here

`https://github.com/shanurrahman/fahm/blob/feat/azure/frontend/utils/makechain.ts` >
`https://github.com/shanurrahman/fahm/blob/feat/azure/frontend/utils/getModel.ts`.

I would really appreciate if someone can show me a working example

**Comment by shanurrahman** [comment]
Here is a restructured and rephrased version:

To get the code working, you need to set up two separate deployments on Azure: one for embeddings and one for chat completions. Make sure to properly set the environment variables `AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME` and `AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME` to point to the correct deployments. If issues persist, remove any other deployment options you may have previously configured.  

The code was calling the embeddings endpoint but pointing to the base URL of the completions deployment to get the embeddings. The relevant code is:

```
  const chain = ConversationalRetrievalQAChain.fromLLM(
    azureModel,
    vectorstore.asRetriever(),
    {
      qaTemplate: QA_PROMPT,
      questionGeneratorTemplate: CONDENSE_PROMPT,
      returnSourceDocuments: true, //The number of source documents returned is 4 by default
    },
  );
```

The required environment variables are:

```
AZURE_OPENAI_API_KEY=**

AZURE_OPENAI_API_INSTANCE_NAME=**  

AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME=**  

AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME=**

AZURE_OPENAI_API_VERSION=2023-03-15-preview
```

Reference: Azure Playground 

<img width="1215" alt="Screen Shot 2023-07-08 at 8 10 12 AM" src="https://github.com/hwchase17/langchainjs/assets/17947802/52f85900-c002-470f-b1d5-c0a891b63598">
