### ISSUE TITLE
RequestsGetTool: fetch is not defined

### ISSUE THREAD

**Issue by nirajmchauhan** [hwchase17/langchainjs#1888]
I am trying to write a basic agent that calls the public API, when I run it, it gives me following error:

```
ReferenceError: fetch is not defined
    at RequestsGetTool._call (node_modules/langchain/dist/tools/requests.cjs:37:21)
    at RequestsGetTool.call (node_modules/langchain/dist/tools/base.cjs:29:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node_modules/langchain/dist/agents/executor.cjs:104:23
```

My code:
```
import "dotenv/config";
import { initializeAgentExecutorWithOptions } from "langchain/agents";
import { OpenAI } from "langchain/llms/openai";
import { RequestsGetTool } from "langchain/tools";

export const run = async () => {
  const model = new OpenAI({ temperature: 0 });

  const endpoint = "https://jsonplaceholder.typicode.com/todos/1";

  const getTool = new RequestsGetTool();

  const executor = await initializeAgentExecutorWithOptions([getTool], model, {
    agentType: "zero-shot-react-description",
    verbose: true,
  });

  console.log("Loaded agent.");

  const input = `Make a GET request to ${endpoint}`;

  console.log(`Executing with input "${input}"...`);

  const result = await executor.call({ input });

  console.log(result);
};

run().then();

```

**Comment by jacoblee93** [comment]
What environment are you running?

**Comment by nirajmchauhan** [comment]
I was using Node16, thanks.
