### ISSUE TITLE
Could not parse LLM output

### ISSUE THREAD

**Issue by nirajmchauhan** [hwchase17/langchainjs#1895]
I am trying out custom agents. I have added 3 tools `RequestsGetTool`, `JsonListKeysTool` & `JsonGetValueTool`. I am trying out `https://jsonplaceholder.typicode.com/todos` API to get all todos title.

I am getting error as `Error: Could not parse LLM output: 
```
Error: Could not parse LLM output: I need to make an API call to get the list of all TODOs. I can use the requests_get tool to do that. Once I have the response, I will need to extract the titles of the TODOs and return them. I can use the json_list_keys tool to find the path to the titles in the JSON response. And finally, I can use the json_get_value tool to get the values of the titles.
    at ZeroShotAgentOutputParser.parse (node_modules/langchain/dist/agents/mrkl/outputParser.cjs:35:19)
    at ZeroShotAgent._plan (node_modules/langchain/dist/agents/agent.cjs:215:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentExecutor._call (node_modules/langchain/dist/agents/executor.cjs:88:28)
    at async AgentExecutor.call (node_modules/langchain/dist/chains/base.cjs:90:28)
    at async AgentExecutor.run (node_modules/langchain/dist/chains/base.cjs:59:30)
    at async run (agent.ts:85:20)
``` 

[OpenAPI file](https://gist.github.com/nirajmchauhan/de7550fa2d58440c5773e94fd8f35abe)

My code:
```ts
const run = async () => {
  let data: JsonObject;
  try {
    const yamlFile = fs.readFileSync("openapi.yaml", "utf8");
    data = yaml.load(yamlFile) as JsonObject;
    if (!data) {
      throw new Error("Failed to load OpenAPI spec");
    }
  } catch (e) {
    console.error(e);
    return;
  }

  const tools = [
    new RequestsGetTool(),
    new JsonListKeysTool(new JsonSpec(data)),
    new JsonGetValueTool(new JsonSpec(data)),
  ];

  const prompt = ZeroShotAgent.createPrompt(tools, {
    prefix: `You are a support person that manages TODOs list from https://jsonplaceholder.typicode.com/todos.
    When a request comes for getting list of all TODOs then make the API call and respond with all TODOs title. You have access to the following tools:`,
  });

  const chatPrompt = ChatPromptTemplate.fromPromptMessages([
    new SystemMessagePromptTemplate(prompt),
    HumanMessagePromptTemplate.fromTemplate(`{input}

This was your previous work (but I haven't seen any of it! I only see what you return as final answer):
{agent_scratchpad}`),
  ]);

  const chat = new ChatOpenAI({
    maxRetries: 2,
  });

  const llmChain = new LLMChain({
    prompt: chatPrompt,
    llm: chat,
  });

  const agent = new ZeroShotAgent({
    llmChain,
    allowedTools: tools.map((tool) => tool.name),
  });

  const executor = AgentExecutor.fromAgentAndTools({
    agent,
    tools,
    verbose: true,
  });

  const response = await executor.run("Get me all the TODOs?");

  console.log(response);
};

run().then();
```

**Comment by jacoblee93** [comment]
I would suggest setting the `temperature` to 0 to reduce formatting issues and/or trying out the new `openai-functions` agent:

https://js.langchain.com/docs/modules/agents/agents/action/openai
