### ISSUE TITLE
Langchain doesn't work on AWS Lambda with either faiss or hnswlib

### ISSUE THREAD

**Issue by dmb0058** [hwchase17/langchainjs#1930]
The current version is broken on AWS lambda, both with Faiss and HNSWlib. I've spent the last few days building test cases on both platforms, but haven't dived into the langchain code.

The typical outcome is:

"Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.\n\nError: libgomp.so.1: cannot open shared object file: No such file or directory"

Same with HNSWlib (substitute hnswlib for faiss in the error above).

Also see

https://github.com/hwchase17/langchainjs/issues/943
https://github.com/hwchase17/langchainjs/issues/1764

Hope this helps - langchain is amazing, and if it worked on AWS it would be even better :)

David

**Comment by dmb0058** [comment]
I think this might be a work-around, though it fell apart at

cp /usr/lib64/libgomp.so.1 /lambda-layer/lib/

I was lost in a sub-shell, in a directory I haven’t been able to debug yet, but I’ll have a look and see if I can tease the hints in the posts apart.

Thanks for your help :)

David

**Comment by dmb0058** [comment]
Hi,

I successfully built a libgomp layer and attached it to my lambda (I don’t know it I did this correctly, as I selected Node 18.x as the runtime?)

Unfortunately the end result is very similar: looks like glibc_2.27 is also “missing”? This whole thing smells of hackery and “nowhere ready for production” :) 

Thanks anyway,

David 

{
  "errorType": "Error",
  "errorMessage": "Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.\n\nError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/nodejs/node_modules/faiss-node/build/Release/faiss-node.node)",
  "trace": [
    "Error: Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.",
    "",
    "Error: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/nodejs/node_modules/faiss-node/build/Release/faiss-node.node)",
    "    at FaissStore.importFaiss (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:236:19)",
    "    at async readIndex (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:141:37)",
    "    at async Promise.all (index 1)",
    "    at async FaissStore.load (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:144:51)",
    "    at async query (/var/task/index.js:112:20)",
    "    at async exports.handler (/var/task/index.js:20:9)"
  ]
}

**Comment by jacoblee93** [comment]
Pinging @ewfian - is this something fixable in `faiss-node`?

**Comment by ewfian** [comment]
@jacoblee93 There is also a [related issue](https://github.com/ewfian/faiss-node/issues/25) on faiss-node side. I'll do some research and try to find a solution.

**Comment by dmb0058** [comment]
Happy to test any new versions if it helps :)

**Comment by lika85456** [comment]
There is a [document](https://github.com/yoshoku/hnswlib-node/wiki/How-to-run-hnswlib-node-on-AWS-Lambda) on how to run hnswlib-node on AWS lambda. I managed to deploy it using this dockerfile:
```dockerfile
FROM public.ecr.aws/lambda/nodejs:18 as builder
WORKDIR /usr/app

# install python
RUN yum install -y python3 make gcc-c++ && \
    yum clean all && \
    rm -rf /var/cache/yum

# install pnpm
RUN npm i -g pnpm

# install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# build
COPY index.ts ./
RUN pnpm run build


FROM public.ecr.aws/lambda/nodejs:18
WORKDIR ${LAMBDA_TASK_ROOT}

COPY foo.dat ./
COPY --from=builder /usr/app ./
COPY --from=builder /usr/app/dist/* ./

CMD ["index.handler"]
```

Looking for a lambda layer solution, since I don't want to deploy using Docker images.

**Comment by dmb0058** [comment]
Amazon linux 2 image seems to only include /lib64/libm.so.6: version `GLIBC_2.26'

Any idea where I might find 2.27 just to see if adding it to my missing libraries layer would work? If not I'll spin up an EC2 server and build one.

**Comment by dmb0058** [comment]
> Hi, I successfully built a libgomp layer and attached it to my lambda (I don’t know if I did this correctly, as I selected Node 18.x as the runtime?) Unfortunately the end result is very similar: looks like libm.so.6 is also “missing”? This whole thing smells of hackery and “nowhere ready for production” :) EDIT: I checked for libm.so.6 in the Docker container but 2.26 is installed so I don't think this is really going anywhere. I guess it's a case of waiting until langchainjs and AWS Lambda work together, or just giving up on langchain as it's just as broken with hnswlib, for I guess the same reason. Thanks anyway, David { "errorType": "Error", "errorMessage": "Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.\n\nError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/nodejs/node_modules/faiss-node/build/Release/faiss-node.node)", "trace": [ "Error: Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.", "", "Error: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/nodejs/node_modules/faiss-node/build/Release/faiss-node.node)", " at FaissStore.importFaiss (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:236:19)", " at async readIndex (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:141:37)", " at async Promise.all (index 1)", " at async FaissStore.load (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:144:51)", " at async query (/var/task/index.js:112:20)", " at async exports.handler (/var/task/index.js:20:9)" ] }
> […](#)
> On 11 Jul 2023, at 18:39, dosu-beta[bot] ***@***.***> wrote: zip -r lib.zip lib

I think the problem here might be something to do with the fact that AWS Lambda runs in "Amazon Linux 2", which has glibc 2.26. So in the error above it seems to be saying that faiss-node requires glibc 2.27. If that's the case it might explain why there are unmet dependencies. Unfortunately the only options would appear to be to wait for AWS to update the version of glibc or to get a 'downgraded' version of faiss-node for Lambda.

Or I might be barking at the moon :)

**Comment by campoblanco** [comment]
I'm facing the same issue, and haven't been able to solve it. I would really like to be able to use FAISS and LangChain in a lambda

**Comment by awadhwanan** [comment]
> There is a [document](https://github.com/yoshoku/hnswlib-node/wiki/How-to-run-hnswlib-node-on-AWS-Lambda) on how to run hnswlib-node on AWS lambda. I managed to deploy it using this dockerfile:
> 
> ```dockerfile
> FROM public.ecr.aws/lambda/nodejs:18 as builder
> WORKDIR /usr/app
> 
> # install python
> RUN yum install -y python3 make gcc-c++ && \
>     yum clean all && \
>     rm -rf /var/cache/yum
> 
> # install pnpm
> RUN npm i -g pnpm
> 
> # install dependencies
> COPY package.json pnpm-lock.yaml ./
> RUN pnpm install
> 
> # build
> COPY index.ts ./
> RUN pnpm run build
> 
> 
> FROM public.ecr.aws/lambda/nodejs:18
> WORKDIR ${LAMBDA_TASK_ROOT}
> 
> COPY foo.dat ./
> COPY --from=builder /usr/app ./
> COPY --from=builder /usr/app/dist/* ./
> 
> CMD ["index.handler"]
> ```
> 
> Looking for a lambda layer solution, since I don't want to deploy using Docker images.

@lika85456  This solution fails if you try to do anything with vectorStore
https://js.langchain.com/docs/modules/chains/popular/vector_db_qa

**Comment by ewfian** [comment]
There is some update on faiss-node side, you can try it out, contact me if any questions
https://github.com/ewfian/faiss-node/issues/25#issuecomment-1645315198

**Comment by dmb0058** [comment]
Hi,

No luck my side I’m afraid:

{
  "errorType": "Error",
  "errorMessage": "Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.\n\nError: libgomp.so.1: cannot open shared object file: No such file or directory",
  "trace": [
    "Error: Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.",
    "",
    "Error: libgomp.so.1: cannot open shared object file: No such file or directory",
    "    at FaissStore.importFaiss (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:237:19)",
    "    at async readIndex (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:141:37)",
    "    at async Promise.all (index 1)",
    "    at async FaissStore.load (/opt/nodejs/node_modules/langchain/dist/vectorstores/faiss.cjs:144:51)",
    "    at async query (/var/task/index.js:112:20)",
    "    at async exports.handler (/var/task/index.js:20:9)"
  ]
}

David

**Comment by ewfian** [comment]
@dmb0058 I have made a demo for langchain. Please confirm whether it works properly by uploading this zip directly to AWS.
[langchain-faiss-aws-demo.zip](https://github.com/hwchase17/langchainjs/files/12135795/langchain-faiss-aws-demo.zip)
It should correctly output the total count in the index, which is 1.
![Snipaste_2023-07-22_14-34-47](https://github.com/hwchase17/langchainjs/assets/12423122/0a653043-630e-45e0-a5b9-3537059506e2)

---
If you want your project to work, please remember that the files(node_modules/faiss-node/build/Release) in the zip to upload to AWS should replace with the files I provided here: https://github.com/ewfian/faiss-node/issues/25#issuecomment-1645315198

**Comment by iAmCodeHead** [comment]
facing similar issue.

**Comment by ewfian** [comment]
Here is a new demo
Function: [langchain-aws-demo.zip](https://github.com/hwchase17/langchainjs/files/12140242/langchain-aws-demo.zip)
Layer: [faiss-node-v0.2.2-aws-layer-x64.zip](https://github.com/hwchase17/langchainjs/files/12140243/faiss-node-v0.2.2-aws-layer-x64.zip)

**Comment by 2441630833** [comment]
> The current version is broken on AWS lambda, both with Faiss and HNSWlib. I've spent the last few days building test cases on both platforms, but haven't dived into the langchain code.
> 
> The typical outcome is:
> 
> "Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.\n\nError: libgomp.so.1: cannot open shared object file: No such file or directory"
> 
> Same with HNSWlib (substitute hnswlib for faiss in the error above).
> 
> Also see
> 
> #943 #1764
> 
> Hope this helps - langchain is amazing, and if it worked on AWS it would be even better :)
> 
> David


Hi, it seems you encountered an issue possibly related to the faiss-node or hnswlib dependency in langchain. If you suspect the issue is due to faiss-node or hnswlib depending on third-party dependencies, there's a workaround you can try:

    Remove the faiss-node dependency from your package.json file.
    Modify your Dockerfile to install the faiss-node dependency directly.

If you're using HNSWlib, simply replace faiss with hnswlib in your Dockerfile.

By handling the installation process in the Dockerfile instead of through package.json, you might avoid the issue. I hope this helps!
![图片](https://github.com/hwchase17/langchainjs/assets/102354417/7e2058f1-3afe-4ca2-9802-8344447af883)

**Comment by dmb0058** [comment]
Hey, thanks for checking in.
Let me check - It all works fine if I manually upload the package from git
but I'd really like to use the npm package as that's how everything else in
my pipeline works. Will come back tomorrow with a go/no go.

David

**Comment by Julien-cpsn** [comment]
I am facing the same issue inside of Vue 3 + Vite

**Comment by ashishbamania** [comment]
I have been using Next.js 13 and was getting the same issue ("Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.") with the following code:
        
      const embeddings = new OpenAIEmbeddings({
        openAIApiKey: process.env.OPENAI_API_KEY,
      });

      const vectorStore = await FaissStore.fromDocuments(
        docs,
        embeddings,
      );
        
I fixed it with making these changes to next.config.js file:

    /** @type {import('next').NextConfig} */
    const nextConfig = {
      webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
        config.resolve.alias.canvas = false;
        config.resolve.alias.encoding = false;
        config.externals = [...config.externals, "faiss-node"]; //added this line
        return config;
      },
    };
    
    module.exports = nextConfig;

**Comment by jacoblee93** [comment]
Are you using the edge runtime? `faiss-node` is Node only :(

**Comment by bitsnaps** [comment]
I'm getting the same issue with `faiss-node@^0.5.1` (also tried `^0.2.1` which was working with an old example).
```
...
Error: Could not import faiss-node. Please install faiss-node as a dependency with, e.g. `npm install -S faiss-node`.
...
```
Running locally with Node v18.19.0 LTS on macOS. I used `HuggingFaceInferenceEmbeddings` instead of openai's embeddings.

**Comment by apotox** [comment]
here is an example to how to use / install faiss node on aws lambda https://github.com/apotox/faiss-node-aws-lambda

**Comment by dmb0058** [comment]
Hi,

I never did get it working, apart from the x86 version of faiss that Fan
(ewfian) built (
https://github.com/ewfian/faiss-node/releases/download/v0.5.1/faiss-node-v0.5.1-aws-x64.zip)
which I've used since then.

I couldn't get the equivalent arm64 one to load, and on the odd occasions
where I tried to load newer x86 versions they didn't work either. It seems
to be missing dependencies from what I can remember, but as far as I can
tell this is the only FAISS that works as an AWS lambda layer with
langchainjs.

I gave up completely on HNSWlib.

David
