### ISSUE TITLE
Add Support For Backend requests(Node.js)

### ISSUE THREAD

**Issue by MirzaHasnat** [hwchase17/langchainjs#2041]
hi, 

today i was trying to implement serper api in my node.js application using langchain Serper class, but after the implementation I got an error that:
```
ReferenceError: fetch is not defined
    at Serper._call (D:\Projects\Applied Physics\APQ\chat-with-gpt\server\node_modules\langchain\dist\tools\serper.cjs:62:21)
    at ToolToUse.<anonymous> (D:\Projects\Applied Physics\APQ\chat-with-gpt\server\src\endpoints\service-proxies\langchain\tools\toolToUse.ts:24:33)
    at Generator.next (<anonymous>)
    at D:\Projects\Applied Physics\APQ\chat-with-gpt\server\src\endpoints\service-proxies\langchain\tools\toolToUse.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Projects\Applied Physics\APQ\chat-with-gpt\server\src\endpoints\service-proxies\langchain\tools\toolToUse.ts:4:12)
    at ToolToUse.get_tool_result (D:\Projects\Applied Physics\APQ\chat-with-gpt\server\src\endpoints\service-proxies\langchain\tools\toolToUse.ts:22:16)
    at AutonomousServiceHandler.<anonymous> (D:\Projects\Applied Physics\APQ\chat-with-gpt\server\src\endpoints\service-proxies\langchain\autonomousHandler.ts:92:26)
    at Generator.next (<anonymous>)
    at D:\Projects\Applied Physics\APQ\chat-with-gpt\server\src\endpoints\service-proxies\langchain\autonomousHandler.ts:8:71
 ```
 
 
 so I went to the file where this error was causing issue and I found that langchain is using browser fetch to fetch the result from serper api:
 
![image](https://github.com/hwchase17/langchainjs/assets/40728571/0d1917e6-1eef-40fc-938b-c034632f7abf)

my question is is that possible if we can add node.js support or we can use Axios instead of fetch to retrive results from http requests?

Thank you so much

**Comment by jacoblee93** [comment]
What version of Node are you using? We only support 18 and up, where `fetch` is a global:

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

If you're on 16, you can try this:

https://js.langchain.com/docs/get_started/installation#unsupported-nodejs-16

**Comment by MirzaHasnat** [comment]
Yeah,  I'm using node.js 16.6 

Thank you so much, I got it
