### ISSUE TITLE
openai_functions return No message in generations

### ISSUE THREAD

**Issue by RaflyLesmana3003** [hwchase17/langchainjs#2042]
hello guys, is there any clue what i am facing right know.

i want to use call function in the chain, but end up getting an error.

this is my code
```ts
app.post('/callFunction', async (req, res) => {
    const llm = new oa.OpenAI({
        openAIApiKey: "",
        temperature: 0,
    });
    const chain = await lcchain.createOpenAPIChain(
        "https://gist.githubusercontent.com/roaldnefs/053e505b2b7a807290908fe9aa3e1f00/raw/0a212622ebfef501163f91e23803552411ed00e4/openapi.yaml",{
            llm
        }
    );
    const result = await chain.run(`What's today's comic?`);
    res.status(200).send(result);
})
```

and this is the error message
```
Error: No message in generations [{"text":"[{\"lc\":1,\"type\":\"constructor\",\"id\":[\"langchain\",\"schema\",\"HumanMessage\"],\"kwargs\":{\"content\":\"You can use the provided API's to respond to this user query:\\n\\nWhat's today's comic?\",\"additional_kwargs\":{}}}]"}]
    at OutputFunctionsParser.parseResult (/Users/rafly/Documents/langchain/node_modules/langchain/dist/output_parsers/openai_functions.cjs:44:19)
    at JsonOutputFunctionsParser.parseResult (/Users/rafly/Documents/langchain/node_modules/langchain/dist/output_parsers/openai_functions.cjs:80:48)
    at JsonOutputFunctionsParser.parseResultWithPrompt (/Users/rafly/Documents/langchain/node_modules/langchain/dist/schema/output_parser.cjs:7:21)
    at LLMChain._getFinalOutput (/Users/rafly/Documents/langchain/node_modules/langchain/dist/chains/llm_chain.cjs:93:55)
    at LLMChain._call (/Users/rafly/Documents/langchain/node_modules/langchain/dist/chains/llm_chain.cjs:123:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LLMChain.call (/Users/rafly/Documents/langchain/node_modules/langchain/dist/chains/base.cjs:90:28)
    at async SequentialChain._call (/Users/rafly/Documents/langchain/node_modules/langchain/dist/chains/sequential_chain.cjs:106:21)
    at async SequentialChain.call (/Users/rafly/Documents/langchain/node_modules/langchain/dist/chains/base.cjs:90:28)
    at async SequentialChain.run (/Users/rafly/Documents/langchain/node_modules/langchain/dist/chains/base.cjs:59:30)
```

https://github.com/hwchase17/langchainjs/blob/46e1734be594d30a87548a70f2e7e167d6dd3985/docs/extras/modules/chains/additional/openai_functions/openapi.mdx#L26

**Comment by jacoblee93** [comment]
Use `ChatOpenAI`, functions are only supported by OpenAI chat models like gpt-3.5-turbo and gpt-4
