### ISSUE TITLE
Conversational Retrieval Agents | TypeError: llm._modelType is not a function

### ISSUE THREAD

**Issue by binodev** [hwchase17/langchainjs#2171]
I have an error with the implementation of Conversational Retrieval Agents in Nodejs. 

I'm using the latest version of langchain ( "langchain": "^0.0.122",)

This is my code :

const { OpenAI } = require('langchain/llms/openai');
const { ChatOpenAI } = require("langchain/chat_models/openai") ;
const { ConversationalRetrievalQAChain } = require('langchain/chains');
const { ConversationChain }= require( "langchain/chains");
const { createRetrieverTool }= require("langchain/agents/toolkits");
const { createConversationalRetrievalAgent } = require("langchain/agents/toolkits");
const { OpenAIAgentTokenBufferMemory } = require ("langchain/agents/toolkits");
const { initializeAgentExecutorWithOptions } = require ("langchain/agents");
const { DynamicTool }= require("langchain/tools");

const llm = new ChatOpenAI({
  temperature: 0,
  maxTokens: 300,
  modelName: 'gpt-3.5-turbo',
});
const memory = new OpenAIAgentTokenBufferMemory({
  llm: llm,
  memoryKey: "chat_history",
  returnMessages: true,
  inputKey:"input",
  outputKey:"output",
});

const makeChain = async (vectorstore,basePrompt) => {
  
  const retriever = vectorstore.asRetriever();

const tool = createRetrieverTool(retriever, {
  name: "search_state_of_union",
  description: "Searches and returns documents regarding the state-of-the-union.",
});
const tools = [tool]

  const chain = await initializeAgentExecutorWithOptions(llm,tools,{
    verbose: true,
    agentType: "openai-functions",
    memory:memory,
    returnIntermediateSteps: true,
    agentArgs: {
      prefix:basePrompt +` `+`Do your best to answer the questions. Feel free to use any tools available to look up relevant information, only if necessary.`,
    },
  });
  return chain;
};

module.exports ={
    makeChain
}

this is the error : 

TypeError: llm._modelType is not a function
    at OpenAIAgent.fromLLMAndTools (/home/binodev/my-projects/nestor/api/node_modules/langchain/dist/agents/openai/index.cjs:88:17)
    at initializeAgentExecutorWithOptions (/home/binodev/my-projects/nestor/api/node_modules/langchain/dist/agents/initialize.cjs:106:47)
    at makeChain (/home/binodev/my-projects/nestor/api/utils/makechain.js:35:23)
    at Object.handler (/home/binodev/my-projects/nestor/api/models/chatbot.js:273:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/binodev/my-projects/nestor/api/api/routes/resource.js:161:16

**Comment by binodev** [comment]
Thank you for your answer. I was able to resolve the error by positioning the parameters of initializeAgentExecutorWithOptions correctly. Here's the correction:     const chain = await initializeAgentExecutorWithOptions(tools,llm,{
    verbose: true,
    agentType: "openai-functions",
    memory:memory,
    returnIntermediateSteps: true,
    agentArgs: {
      prefix:basePrompt +` `+`Do your best to answer the questions. Feel free to use any tools available to look up relevant information, only if necessary.`,
    },
  });
