### ISSUE TITLE
Deno: Could not import hnswlib-node. Please install hnswlib-node as a dependency with, e.g. `npm install -S hnswlib-node`

### ISSUE THREAD

**Issue by NoRabbit** [hwchase17/langchainjs#2207]
Hi,

I have a problem using hnswlib with Deno. It gives me the error:

Error: Could not import hnswlib-node. Please install hnswlib-node as a dependency with, e.g. `npm install -S hnswlib-node`.

Error: module "path_to_my_project_directory**\build\addon.node**" not found
    at Function.imports (https://esm.sh/v130/langchain@0.0.124/denonext/vectorstores/hnswlib.js:5:9073)
    at async Function.getHierarchicalNSW (https://esm.sh/v130/langchain@0.0.124/denonext/vectorstores/hnswlib.js:5:6083)
    at async initIndex (https://esm.sh/v130/langchain@0.0.124/denonext/vectorstores/hnswlib.js:5:6419)
    at async i.addVectors (https://esm.sh/v130/langchain@0.0.124/denonext/vectorstores/hnswlib.js:5:6724)
    at async Function.fromDocuments (https://esm.sh/v130/langchain@0.0.124/denonext/vectorstores/hnswlib.js:5:8879)
    at async digestDocument (file:///D:/PROJETS/recruit%20gpt/src/digest-doc.ts:53:25)
    at async file:///D:/PROJETS/recruit%20gpt/src/digest-doc.ts:83:17

I import the lib like so:
import { HNSWLib } from "https://esm.sh/langchain/vectorstores/hnswlib"

I also tried installing hnswlib-node with npm, even though I'm using deno. Didn't work.

The weird thing is that it tries to get a module in "\build\addon.node" from the root directory of my project... (see error above).
Thx for the help.

**Comment by NoRabbit** [comment]
I also tried to manually copy the files inside my "node_modules\hnswlib-node\build\Release" directory to the one specified above in the error "\build\". Not working either. Same error as above.

**Comment by NoRabbit** [comment]
Ok. I just saw that it was for node only.... my bad

**Comment by dominicdev** [comment]
got this too how to fix this ?

`⨯ Error: Could not import hnswlib-node. Please install hnswlib-node as a dependency with, e.g. `npm install -S hnswlib-node`.

Error: Cannot find package 'hnswlib-node' imported from D:\Documents\work\nextJS13\next-rag-app\node_modules\langchain\dist\vectorstores\hnswlib.cjs
    at HNSWLib.imports (D:\Documents\work\nextJS13\next-rag-app\node_modules\langchain\dist\vectorstores\hnswlib.cjs:271:19)`
