### ISSUE TITLE
Issue with mivuls DB

### ISSUE THREAD

**Issue by Biigode** [hwchase17/langchainjs#2314]
I'm encountering an error whenever I attempt to send an embedding to Milvus.

```
file:///home/victorf/projects/study/langchainjs/node_modules/langchain/dist/vectorstores/milvus.js:246
        const hasColResp = await this.colMgr.hasCollection({
                                             ^

TypeError: Cannot read properties of undefined (reading 'hasCollection')
    at Milvus.ensureCollection (file:///home/victorf/projects/study/langchainjs/node_modules/langchain/dist/vectorstores/milvus.js:246:46)
    at Milvus.addVectors (file:///home/victorf/projects/study/langchainjs/node_modules/langchain/dist/vectorstores/milvus.js:138:20)
    at Milvus.addDocuments (file:///home/victorf/projects/study/langchainjs/node_modules/langchain/dist/vectorstores/milvus.js:132:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.fromDocuments (file:///home/victorf/projects/study/langchainjs/node_modules/langchain/dist/vectorstores/milvus.js:356:9)
    at async file:///home/victorf/projects/study/langchainjs/langWithMilvus.js:43:21
```
Here is my code:

```
import { PDFLoader } from "langchain/document_loaders/fs/pdf";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";
import { Milvus } from "langchain/vectorstores/milvus";

const embeddings = new OpenAIEmbeddings({
  azureOpenAIApiDeploymentName: "<FOO>",
  azureOpenAIApiInstanceName:"<FOO>",
  azureOpenAIApiKey: "<FOO>"
  azureOpenAIApiVersion: "<FOO>",
});


const loader = new PDFLoader("./bcff11.pdf");
const docs = await loader.load();
const vectorStore = await Milvus.fromDocuments(docs, embeddings, {
  url: "<FOO>:<BAR>",
  collectionName: "docs",
});

const response = await vectorStore.similaritySearch("scared", 2);

console.log(response);
```

**Comment by Biigode** [comment]
Still not work

**Comment by jacoblee93** [comment]
What version of milvus do you have installed? Can you try updating?

**Comment by Biigode** [comment]
I'm using this version "^2.2.24"
![image](https://github.com/hwchase17/langchainjs/assets/36681261/5f33381d-61f1-4443-8908-e5ef9570433f)

**Comment by jacoblee93** [comment]
Ah can you update your LangChain dep to latest? Milvus had a breaking change a while back.

**Comment by Biigode** [comment]
The problem with milvus was resolved when i update my node version to 18LTS.
Thanks
