### ISSUE TITLE
ChatConversationalAgentOutputParser fails when there is a JSON code snippet inside the final response

### ISSUE THREAD

**Issue by Cesar-M-Diaz** [hwchase17/langchainjs#2363]
**Title:** Failed Parsing Due to having a JSON code snippet inside the response

Description:
every time that I ask for a package.json code example i got a parser error:

this issue is related to the bug that @italojs reported here:  https://github.com/hwchase17/langchainjs/issues/2322

```
 Failed to parse. Text: "{
    "action": "Final Answer",
    "action_input": "Sure! Here is an example of a package.json file with the necessary commands to connect an app:\n\n```json\n{\n  \"name\": \"my-app\",\n  \"version\": \"1.0.0\",\n  \"description\": \"My Node.js app\",\n  \"main\": \"index.js\",\n  \"scripts\": {\n    \"start\": \"node index.js\"\n  },\n  \"dependencies\": {\n    \"express\": \"^4.17.1\"\n  }\n}\n```"
}". Error: SyntaxError: Unexpected token \ in JSON at position 0
    at ChatConversationalAgentOutputParser.parse (/Users/italojs/dev/nodesource/ns-ai-service/node_modules/langchain/dist/agents/chat_convo/outputParser.cjs:49:19)
    at OutputFixingParser.parse (/Users/italojs/dev/nodesource/ns-ai-service/node_modules/langchain/dist/output_parsers/fix.cjs:55:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentExecutor._call (/Users/italojs/dev/nodesource/ns-ai-service/node_modules/langchain/dist/agents/executor.cjs:88:28)
    at async AgentExecutor.call (/Users/italojs/dev/nodesource/ns-ai-service/node_modules/langchain/dist/chains/base.cjs:90:28) {
  output: undefined
}
```

**Code to reproduce the error:**

```javascript
(async () => {
  const { ChatOpenAI } = require('langchain/chat_models/openai')
  const { initializeAgentExecutorWithOptions } = require('langchain/agents')
  const { Calculator } = require('langchain/tools/calculator')
  const { BufferMemory } = require('langchain/memory')

  const model = new ChatOpenAI({ temperature: 0 })

  const tools = [
    new Calculator()
  ]

  const executor = await initializeAgentExecutorWithOptions(tools, model, {
    agentType: 'chat-conversational-react-description',
    verbose: true,
    memory: new BufferMemory({
      memoryKey: 'chat_history',
      returnMessages: true
    })
  })

  const execAndPrint = async (input) => {
    console.log(`Question: ${input}`)
    const result = await executor.call({ input })
    console.log(`Response: ${result.output}`)
  }

  await execAndPrint('Make a package.json with the necessary commands to connect an app')
})()
``` 
**Proposed Solution**
My proposal is to change the parser filter logic  in the [ChatConversationalAgentOutputParser](https://github.com/hwchase17/langchainjs/blob/7b0bcefb50ca3535d02e655607e5767ac86c151a/langchain/src/agents/chat_convo/outputParser.ts#L28)  to better handle this scenario:

```javascript

    
   export class ChatConversationalAgentOutputParser extends AgentActionOutputParser {
  [...]
  async parse(text: string): Promise<AgentAction | AgentFinish> {
    let jsonOutput = text.trim();
    // modified filter ignores the internal json code snippet
    if (jsonOutput.includes("```json")) {
      const tempString = jsonOutput.split("```json")[1].trimStart();
      if (tempString.includes("action") && tempString.includes("action_input")) {
        jsonOutput = tempString;
        const lastIndex = jsonOutput.lastIndexOf("```");
        if (lastIndex !== -1) {
          jsonOutput = jsonOutput.slice(0, lastIndex).trimEnd();
        }
      }
    } else if (jsonOutput.includes("```")) {
      const firstIndex = jsonOutput.indexOf("```");
      jsonOutput = jsonOutput.slice(firstIndex + 3).trimStart();
      const lastIndex = jsonOutput.lastIndexOf("```");
      if (lastIndex !== -1) {
        jsonOutput = jsonOutput.slice(0, lastIndex).trimEnd();
      }
    }

    try {
      const response = JSON.parse(jsonOutput);

      const { action, action_input } = response;

     [...]
    }
  }
```

this fix handles the rare scenarios where you may find an additional json snippet inside your response

**Comment by kamalkech** [comment]
so can u share how u imlement ChatConversationalAgentOutputParser ?

**Comment by Cesar-M-Diaz** [comment]
Hey @kamalkech this issue was closed with this proposed change https://github.com/langchain-ai/langchainjs/pull/2377
