### ISSUE TITLE
embedding fails in langchain but works for openai

### ISSUE THREAD

**Issue by BingruLin** [hwchase17/langchainjs#2463]
I try to use langchain(0.0.138) to create embedding for strings and I got error as follow:
```
const { OpenAIEmbeddings } = require("langchain/embeddings/openai"); // 0.0.138

const embeddings = new OpenAIEmbeddings({
  apiKey: openAiConfig.apiKey,
  modelName: "text-embedding-ada-002",
}, {
  basePath: openAiConfig.basePath,
});

const embedding = await embeddings.embedQuery(desc);
```

![image](https://github.com/hwchase17/langchainjs/assets/32869377/ad283ecc-a0bf-4cbf-b9fd-23fecbb34c5e)

but when I use openai nodejs libraray directly, the request success, so I think this is a bug for langchain.
```
const openai_1 = require("openai"); // 3.3.0

const clientConfig = new openai_1.Configuration({
  apiKey: openAiConfig.apiKey,
  basePath: openAiConfig.basePath,
});

const openai = new openai_1.OpenAIApi(clientConfig);

async function getEmbedding(str) {
  try {
    const resp = await openai.createEmbedding({
      model: "text-embedding-ada-002",
      input: str,
    });

    return resp.data.data[0].embedding;
  } catch (err) {
    console.error(err);

    throw err;
  }
}
```

**Comment by BingruLin** [comment]
The error is:
```
Error [InsufficientQuotaError]: You exceeded your current quota, please check your plan and billing details.
    at Object.onFailedAttempt (/Users/bingrulin/Documents/alibaba/project/ott/llm/code/test-node-server/node_modules/langchain/dist/util/async_caller.cjs:87:35)
    at RetryOperation._fn (/Users/bingrulin/Documents/alibaba/project/ott/llm/code/test-node-server/node_modules/p-retry/index.js:67:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jacoblee93** [comment]
I would make sure you're using the same key and the same organization.
