### ISSUE TITLE
FaissStore.addVectors - Invalid the first argument type, must be an Array

### ISSUE THREAD

**Issue by danielehrhardt** [hwchase17/langchainjs#2505]
```
[Nest] 20556  - 05.09.2023, 00:08:52   ERROR [ExceptionsHandler] Invalid the first argument type, must be an Array.
TypeError: Invalid the first argument type, must be an Array.
    at FaissStore.addVectors (C:\projects\codext\shopify-chatbot\shopify-chatbot-api\node_modules\langchain\dist\vectorstores\faiss.cjs:125:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.fromDocuments (C:\projects\codext\shopify-chatbot\shopify-chatbot-api\node_modules\langchain\dist\vectorstores\faiss.cjs:320:9)
    at VectorService.createChromaVectorStoreFromUrl (C:\projects\codext\shopify-chatbot\shopify-chatbot-api\src\common\services\vector.service.ts:100:25)
    at AppController.index (C:\projects\codext\shopify-chatbot\shopify-chatbot-api\src\app.controller.ts:45:5)
    at C:\projects\codext\shopify-chatbot\shopify-chatbot-api\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at C:\projects\codext\shopify-chatbot\shopify-chatbot-api\node_modules\@nestjs\core\router\router-proxy.js:9:17
```

**Comment by jacoblee93** [comment]
I suspect the bot's comment is directionally correct but can't really help without seeing your code.

**Comment by danielehrhardt** [comment]
> I suspect the bot's comment is directionally correct but can't really help without seeing your code.
```
   const files = await fs.promises.readdir(projectPath);
    const jsonFiles = files.filter((file) => file.endsWith('.json'));

    const documents: Document[] = [];

    for (const jsonFile of jsonFiles) {
      const fileContent = await fs.promises.readFile(
        path.join(projectPath, jsonFile),
        'utf-8',
      );

      const jsonContent = JSON.parse(fileContent);

      for (const doc of jsonContent) {
        documents.push(
          new Document({
            pageContent: doc.markdown,
            metadata: {
              title: doc.title,
              url: doc.url,
              description: doc.description,
              modifiedDate: doc.modifiedDate,
            },
          }),
        );
      }
    }
    const textSplitter = new MarkdownTextSplitter({
      chunkSize: 500,
      chunkOverlap: 100,
    });
    const splitDocs = await textSplitter.splitDocuments(documents);
    console.log('1');
    const vectorStore = await FaissStore.fromDocuments(
      splitDocs,
      new OpenAIEmbeddings(),
    );
    console.log('2');

```
Until  console.log('1'); everything works and i can see the documents but between 1 and two the error will apprear

JSON Format:
```
[
  {
    "url": "https://test.com",
    "title": "Suchen",
    "description": "abc",
    "modifiedDate": "2023-09-04T21:53:22.603Z",
    "markdown": " "
 }
]
```
.

**Comment by jacoblee93** [comment]
Thank you, will look today!
