### ISSUE TITLE
HNSWLib TypeError: Cannot read properties of undefined (reading 'embedQuery')

### ISSUE THREAD

**Issue by batjko** [hwchase17/langchainjs#2528]
In my CLI tool, I've been using the examples in the docs to use HNSWLib to persist my in-memory store to disk and reload it every time the CLI command is run (instead of loading and embedding the docs every time).

What works:
1. Store gets created successfully.
2. Documents get loaded and split into it successfully.
3. VectorStore persisted correctly (as far as I can see) to disk (using `.save()`)
4. On next execution, the vector store gets loaded back into memory _seemingly_ successfully (no error yet).

But then when I try to do anything with that store (e.g. run a similarity search or use it to execute a query in a chain call), it throws me the below error.

I have checked and I know the query is being passed in properly, and the embeddings object is really so simple I don't think it's possible to do anything wrong with it - at least the `new OpenAIEmbeddings()` thing was passed in normally, as per docs, but maybe I missed something?

Code:
```js
export async function askLLM(question) {
  const modelName = 'gpt-4'
  const maxTokens = 4096
  const temperature = 0.33

  let vectorStore
  try {
    console.debug('Checking for existing vector store file...')
    vectorStore = await HNSWLib.load(storeFolder)
    console.debug(`Loaded from ${storeFolder}.`)
  } catch (error) {
    throw new Error('No vector store found. Please run "load" command first.')
  }

  const model = new OpenAI({ modelName, maxTokens, temperature })
  const chain = RetrievalQAChain.fromLLM(model, vectorStore.asRetriever(), true)

  const response = await chain.call({ // Here is where it dies!
    query: question,
  })

  return response.text
}
```

Output:
```sh
Checking for existing vector store file...
Loaded from hnswlib.

file:///home/pat/dev/myRepo/node_modules/langchain/dist/vectorstores/base.js:103
        const results = await this.similaritySearchVectorWithScore(await this.embeddings.embedQuery(query), k, filter);
                                                                                         ^

TypeError: Cannot read properties of undefined (reading 'embedQuery')
    at HNSWLib.similaritySearch (file:///home/pat/dev/code-grokker2/node_modules/langchain/dist/vectorstores/base.js:103:90)
    at VectorStoreRetriever._getRelevantDocuments (file:///home/pat/dev/code-grokker2/node_modules/langchain/dist/vectorstores/base.js:68:33)
    at VectorStoreRetriever.getRelevantDocuments (file:///home/pat/dev/code-grokker2/node_modules/langchain/dist/schema/retriever.js:66:40)
    at async RetrievalQAChain._call (file:///home/pat/dev/code-grokker2/node_modules/langchain/dist/chains/retrieval_qa.js:55:22)
    at async RetrievalQAChain.call (file:///home/pat/dev/code-grokker2/node_modules/langchain/dist/chains/base.js:101:28)
    at async askLLM (file:///home/pat/dev/code-grokker2/src/app.js:100:20)
    at async Command.<anonymous> (file:///home/pat/dev/code-grokker2/src/cli.js:30:5)
```

Note, it seems to complain, upon calling the chain, that there is no `embeddings` to use for embedding the query.
But I gave it the OpenAI model, which did not complain when creating the store and embedding the documents in the first place. So not sure why it has a problem here.

Any advice would be appreciated.

Persisted store:
![image](https://github.com/hwchase17/langchainjs/assets/7287076/a7235424-ca1c-4937-af4b-11a783863f2c)

Embedded Documents definitely present:
![image](https://github.com/hwchase17/langchainjs/assets/7287076/c4bf6504-a53a-4ad1-a3ba-7519f9a9b24f)

For reference, this is how the store was saved down:
```js
async function storeCodeInVectorDB(splitDocs) {
  // load into memory
  const embeddings = new OpenAIEmbeddings()
  const store = await HNSWLib.fromDocuments(splitDocs, embeddings)

  // save to file
  await store.save(storeFolder)
  console.debug(`Saved vector store to ${storeFolder}.`)
  return store
}
```

**Comment by batjko** [comment]
Bloody hell, @dosu-beta is right.

The typings on HNSWLib.load(), show that I need to pass in an embeddings object to it and that's what I forgot.

So adding this immediately fixed it for me:

![image](https://github.com/hwchase17/langchainjs/assets/7287076/04d61c27-8d57-4805-8e1e-94534cc32d96)


Thanks, @dosu-beta. 🙏

**Comment by batjko** [comment]
Useful explanation, thank you. 
I guess I assumed the persisted store would have embeddings information in it, but didn't really think about it.

Whoever created this bot, make money with it! It's awesome!
