### ISSUE TITLE
Cannot read properties of undefined (reading embedQuery)

### ISSUE THREAD

**Issue by darshanhande11** [hwchase17/langchainjs#2549]
I am getting the following error when I am using VectorDBQAChain as a tool to the agent.
```
TypeError: Cannot read properties of undefined (reading 'embedQuery')
at HNSWLib.similaritySearch (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/vectorstores/base.cjs:107:90)
at VectorStoreRetriever._getRelevantDocuments (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/vectorstores/base.cjs:71:33)     
at VectorStoreRetriever.getRelevantDocuments (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/schema/retriever.cjs:72:40)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at RetrievalQAChain._call (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/chains/retrieval_qa.cjs:58:22)
at RetrievalQAChain.call (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/chains/base.cjs:104:28)
at RetrievalQAChain.run (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/chains/base.cjs:69:30)
at ChainTool.call (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/tools/base.cjs:50:22)
at /Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/agents/executor.cjs:113:23
at async Promise.all (index 0)
at AgentExecutor._call (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/agents/executor.cjs:109:30)
at AgentExecutor.call (/Users/darshanhande/Documents/opensource/Application/node_modules/langchain/dist/chains/base.cjs:104:28)
```
Following is the code which I have used.

```
const vectorStore = await HNSWLib.load("./src/vector_store");
const chain = VectorDBQAChain.fromLLM(model, vectorStore);
const qaTool = new ChainTool({
    name: "course-data-qa",
    description: "Course Data QA - useful to generate actionable steps for improvement based on the course data after going through the given question and answer ",
    chain,
})
const tools = [
    qaTool,
];
const executor = await initializeAgentExecutorWithOptions(tools, model, {
    agentType: 'chat-conversational-react-description'
  });
const agentInput = `
  Based on the question and the answer, provide relevant feedback and actionable steps to get better at communicating.
  Question : ${ques}
  Answer : ${ans}
  Provide response in HTML Document format.
`;
  const agentResponse = await executor.call({ input: agentInput });
  console.log(agentResponse);
```

**Comment by darshanhande11** [comment]
@dosu-bot Please take a look at the update description of the issue and let me know how to fix the issue.

**Comment by darshanhande11** [comment]
thanks @dosu-bot The above fixes helped, closing the issue.
