### ISSUE TITLE
t.replaceAll is not a function when using "PineconeStore.fromDocuments"

### ISSUE THREAD

**Issue by mongomoe** [hwchase17/langchainjs#471]
Hi, I'm getting the following error when trying to run `PineconeStore.fromDocuments()`

I'm on:
- Node.js version 19 (though I noticed this issue with version 18)
- langchain version 0.0.41
- @pinecone-database/pinecone version 0.0.11

```
TypeError: t.replaceAll is not a function
    at /<project-path>/node_modules/langchain/dist/embeddings/openai.js:59:79
    at Array.map (<anonymous>)
    at OpenAIEmbeddings.embedDocuments (/<project-path>/node_modules/langchain/dist/embeddings/openai.js:59:66)
    at PineconeStore.addDocuments (/<project-path>/node_modules/langchain/dist/vectorstores/pinecone.js:39:54)
    at PineconeStore.fromDocuments (/<project-path>/node_modules/langchain/dist/vectorstores/pinecone.js:111:24)
    at main (/<project-path>/app.js:91:45)
TypeError: t.replaceAll is not a function
    at /<project-path>/node_modules/langchain/dist/embeddings/openai.js:59:79
    at Array.map (<anonymous>)
    at OpenAIEmbeddings.embedDocuments (/<project-path>/node_modules/langchain/dist/embeddings/openai.js:59:66)
    at PineconeStore.addDocuments (/<project-path>/node_modules/langchain/dist/vectorstores/pinecone.js:39:54)
    at PineconeStore.fromDocuments (/<project-path>/node_modules/langchain/dist/vectorstores/pinecone.js:111:24)
    at main (/<project-path>/app.js:91:45)
```

Here is my code:

```
  const docs = [
    new Document({
      metadata: { foo: "bar" },
      pageContent: "pinecone is a vector db",
    }),
    new Document({
      metadata: { foo: "bar" },
      pageContent: "the quick brown fox jumped over the lazy dog",
    }),
    new Document({
      metadata: { baz: "qux" },
      pageContent: "lorem ipsum dolor sit amet",
    }),
    new Document({
      metadata: { baz: "qux" },
      pageContent: "pinecones are the woody fruiting body and of a pine tree",
    }),
  ];

  const embeddings = new OpenAIEmbeddings();

  const pineconeIndex = pinecone.Index("example-index");

  const pineConeStore = await PineconeStore.fromDocuments(docs, embeddings, {
    pineconeIndex,
  });
```

**Comment by fandyaditya** [comment]
I encounter this issue when I accidentally use node 16. Switching it back to node 18 and fixing it.

- node: v18.15.0
- npm:  v9.5.0
- @pinecone-database/pinecone: ^0.0.10
- langchain: 0.0.41
- openai": "^3.2.1:

**Comment by loversama** [comment]
Did you ever fix this, I am getting the same..

```
TypeError: text.replaceAll is not a function
    at OpenAIEmbeddings.embedQuery (D:\Projects\ai-assistant\node_modules\langchain\dist\embeddings\openai.cjs:91:46)
    at PineconeStore.similaritySearch (D:\Projects\ai-assistant\node_modules\langchain\dist\vectorstores\base.cjs:41:90)
    at VectorDBQAChain._call (D:\Projects\ai-assistant\node_modules\langchain\dist\chains\vector_db_qa.cjs:62:45)
    at VectorDBQAChain.call (D:\Projects\ai-assistant\node_modules\langchain\dist\chains\base.cjs:64:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getOpenAIResponse (D:\Projects\ai-assistant\sockets\handlers\openai-chat-pinecone.js:133:24)
    at async Socket.<anonymous> (D:\Projects\ai-assistant\sockets\handlers\socket-rooms.js:55:30)
D:\Projects\ai-assistant\sockets\handlers\openai-chat-pinecone.js:144
      throw new Error('Error processing the request');
            ^

Error: Error processing the request
    at getOpenAIResponse (D:\Projects\ai-assistant\sockets\handlers\openai-chat-pinecone.js:144:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Socket.<anonymous> (D:\Projects\ai-assistant\sockets\handlers\socket-rooms.js:55:30)

**Node.js v19.8.1**
```

 I can confirm I am running the latest Node.js v19.8.1..
