### ISSUE TITLE
Getting "ReferenceError: Headers is not defined" when running langchain examples

### ISSUE THREAD

**Issue by bpulito** [hwchase17/langchainjs#557]
I've tried to setup and use langchain in several different environments and I always get the same error when running any of the examples:

(node:14511) UnhandledPromiseRejectionWarning: ReferenceError: Headers is not defined
    at createRequest (file:///Users/brian_pulitous.ibm.com/git/wa-langchain-extension/node_modules/langchain/src/util/axios-fetch-adapter.js:275:19)
    at fetchAdapter (file:///Users/brian_pulitous.ibm.com/git/wa-langchain-extension/node_modules/langchain/src/util/axios-fetch-adapter.js:202:19)
    at dispatchRequest (/Users/brian_pulitous.ibm.com/git/wa-langchain-extension/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/Users/brian_pulitous.ibm.com/git/wa-langchain-extension/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/Users/brian_pulitous.ibm.com/git/wa-langchain-extension/node_modules/axios/lib/helpers/bind.js:9:15)
    at /Users/brian_pulitous.ibm.com/git/wa-langchain-extension/node_modules/openai/dist/common.js:149:22
    at /Users/brian_pulitous.ibm.com/git/wa-langchain-extension/node_modules/openai/dist/api.js:1761:125

Any ideas what the issue might be?

**Comment by bpulito** [comment]
Sorry, I figured this out. I wasn't running a recent version of Node. It works now.

**Comment by lengocgiang** [comment]
For anyone who is using the Mocha Test Explorer in VSCode and encounters this error, please switch to either Node@18 or Node@19. Additionally, configure the VSCode settings for Mocha using the following code:
```
"mochaExplorer.nodePath": "/opt/homebrew/opt/node@19/bin/node"
```
You can also change it to Node@18 as per your requirement.
