### ISSUE TITLE
[Feature Request] BunJs Support 

### ISSUE THREAD

**Issue by LuisMalhadas** [hwchase17/langchainjs#798]
I have been working with [BunJS](https://bun.sh) runtime and decided to try langchain with it.
I also noted in documentation that there are some supported runtimes...
Also this [discussion](https://github.com/hwchase17/langchainjs/discussions/152) (pointed to me by @homanp) has someone stating it supports it, but not every part.
So it seems that it is not fully compatible with Bun... It imports, instantiates the model, but doesn't execute it.
Am I doing something wrong?
```typescript
import { OpenAI } from "langchain/llms/openai";
console.log("imported");
const model = new OpenAI({ openAIApiKey: "sk-...", temperature: 0.7 });
console.log("model created")
const res = await model.call(
    "What would be a good company name a company that makes colorful socks?"
);
console.log(res);
```
Running the example:
```shell
% bun index.ts
imported
model created
38 |         const PQueue = "default" in PQueueMod ? PQueueMod.default : PQueueMod;
39 |         this.queue = new PQueue({ concurrency: this.maxConcurrency });
40 |     }
41 |     // eslint-disable-next-line @typescript-eslint/no-explicit-any
42 |     call(callable, ...args) {
43 |         return this.queue.add(() => pRetry(() => callable(...args).catch((error) => {
                   ^
TypeError: undefined is not a function (near '...this.queue.add...')
      at call (/Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/util/async_caller.js:43:15)
      at /Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/openai.js:312:15
      at completionWithRetry (/Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/openai.js:300:30)
      at /Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/openai.js:270:24
      at _generate (/Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/openai.js:204:20)
      at /Users/luismal/Projects/bunjs+langchainjs/node_modules/langchain/dist/llms/base.js:43:27
```

**Comment by shanginn** [comment]
same here.

although I had it working [here](https://github.com/shanginn/git-aicommit/blob/1cda50f5bdede80d53e4ec8e6608f222c2a3f82a/autocommit.js), but now I'm trying to do [summarization example](https://js.langchain.com/docs/modules/chains/other_chains/summarization) and it does not work with Bun

**Comment by AlexZoningOut** [comment]
Is it working now?

**Comment by JamesClarke7283** [comment]
> Is it working now?

It works for me.

```
➜  LangChainUtils bun src/test-bun.js        
imported
model created

"RainbowTread Socks" or "VibrantSoles Co."
```
