### ISSUE TITLE
UnhandledPromiseRejectionWarning when deploying to render.com

### ISSUE THREAD

**Issue by AaronMeyers** [hwchase17/langchainjs#801]
My project works fine locally, but i'm having an issue when I deploy it to a render.com server.

When I make a call using a ConversationChain, I get this error:

```
Apr 14 04:09:03 PM  (node:94) UnhandledPromiseRejectionWarning: ReferenceError: Headers is not defined
Apr 14 04:09:03 PM      at createRequest (file:///opt/render/project/src/node_modules/langchain/dist/util/axios-fetch-adapter.js:234:21)
Apr 14 04:09:03 PM      at fetchAdapter (file:///opt/render/project/src/node_modules/langchain/dist/util/axios-fetch-adapter.js:164:21)
Apr 14 04:09:03 PM      at dispatchRequest (/opt/render/project/src/node_modules/axios/lib/core/dispatchRequest.js:58:10)
Apr 14 04:09:03 PM      at Axios.request (/opt/render/project/src/node_modules/axios/lib/core/Axios.js:108:15)
Apr 14 04:09:03 PM      at Function.wrap [as request] (/opt/render/project/src/node_modules/axios/lib/helpers/bind.js:9:15)
Apr 14 04:09:03 PM      at /opt/render/project/src/node_modules/openai/dist/common.js:149:22
Apr 14 04:09:03 PM      at /opt/render/project/src/node_modules/openai/dist/api.js:1738:133
Apr 14 04:09:03 PM  (Use `node --trace-warnings ...` to show where the warning was created)
Apr 14 04:09:03 PM  (node:94) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
Apr 14 04:09:03 PM  (node:94) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The line in my code looks like this:

```
let response = await chain.call({
  userInput: userInput
});
```

I made sure that the server is running node 18.

Any idea what's going on here?

**Comment by AaronMeyers** [comment]
ok i got around this by bumping up the node version from 18.12 to 18.13. Also found that it works with node 19.
