### ISSUE TITLE
Langchain/sql_db with postgress error Axios - ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by AtotheY** [hwchase17/langchainjs#822]
Hey there!

Having some trouble getting langchain/sql_db to work with my PG db. I've followed the tutorial, and below is my code (keys and db info hidden ofc).

Error: 

```
Executing with input "List the top 10 teams by rank"...
/Users/anthony/Dev/rib/chain/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:243
    const headers = new Headers(config.headers);
                    ^
ReferenceError: Headers is not defined
    at createRequest (/Users/anthony/Dev/rib/chain/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:243:21)
    at fetchAdapter (/Users/anthony/Dev/rib/chain/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:170:21)
    at dispatchRequest (/Users/anthony/Dev/rib/chain/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/Users/anthony/Dev/rib/chain/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/Users/anthony/Dev/rib/chain/node_modules/axios/lib/helpers/bind.js:9:15)
    at /Users/anthony/Dev/rib/chain/node_modules/openai/dist/common.js:149:22
    at /Users/anthony/Dev/rib/chain/node_modules/openai/dist/api.js:1761:125
    at async RetryOperation._fn (/Users/anthony/Dev/rib/chain/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 7,
  retriesLeft: 0
}
```

My code:
``` ts
import { OpenAI } from "langchain/llms/openai";
import { SqlDatabase } from "langchain/sql_db";
import { createSqlAgent, SqlToolkit } from "langchain/agents";
import { DataSource } from "typeorm";

/** This example uses Chinook database, which is a sample database available for SQL Server, Oracle, MySQL, etc.
 * To set it up follow the instructions on https://database.guide/2-sample-databases-sqlite/, placing the .db file
 * in the examples folder.
 */

export const run = async () => {
  const datasource = new DataSource({
    type: "postgres",
    host: PGHOST,
    port: PGPORT,
    username: PGUSER,
    password: PGPASSWORD,
    database: PGDATABASE,
  });
  const db = await SqlDatabase.fromDataSourceParams({
    appDataSource: datasource,
  });
  const toolkit = new SqlToolkit(db);

  const model = new OpenAI({
    temperature: 0,
    openAIApiKey: "my-key",
  });
  const executor = createSqlAgent(model, toolkit);

  const input = `List the top 10 teams by rank`;

  console.log(`Executing with input "${input}"...`);

  const result = await executor.call({ input });

  console.log(`Got output ${result.output}`);

  console.log(
    `Got intermediate steps ${JSON.stringify(
      result.intermediateSteps,
      null,
      2
    )}`
  );

  await datasource.destroy();
};

run();
```

**Comment by nfcampos** [comment]
That sounds like you're running this in Node 16, which isn't supported, see https://js.langchain.com/docs/getting-started/install#unsupported-nodejs-16
