### ISSUE TITLE
Zod and Enum support

### ISSUE THREAD

**Issue by baloodevil** [hwchase17/langchainjs#913]
It appears LangChain JS supports Zod enums...
https://github.com/hwchase17/langchainjs/blob/f78f2e90e95878da7c6067fd52e6a75eb0efb5fd/langchain/src/output_parsers/structured.ts#L25-L29

However an error is thrown when using them.  To replicate...
```ts
import { z } from "zod";
import { StructuredOutputParser } from "langchain/output_parsers";

// enum YN {
//   Y = "Y",
//   N = "N",
// }

//const myDesiredResponseFormat = z.nativeEnum(YN).describe("Answer with only a 'Y' or 'N'");
const myDesiredResponseFormat = z.enum(["Y", "N"]).describe("Answer with only a 'Y' or 'N'");

export const run = async () => {
  const parser = StructuredOutputParser.fromZodSchema(myDesiredResponseFormat);
  const foo = parser.getFormatInstructions();
};
```

Which throws...
```
file:///C:/Users/.../apps/langchain-playground/node_modules/langchain/dist/output_parsers/structured.js:44
    throw new Error(`Unsupported type: ${schema._def.innerType.typeName}`);
                                                               ^
TypeError: Cannot read properties of undefined (reading 'typeName')
    at printSchema (file:///C:/Users/.../apps/langchain-playground/node_modules/langchain/dist/output_parsers/structured.js:44:64)
    at StructuredOutputParser.getFormatInstructions (file:///C:/Users/.../apps/langchain-playground/node_modules/langchain/dist/output_parsers/structured.js:67:3)
    at run (file:///C:/Users/.../apps/langchain-playground/src/ReplicateIssue.ts:14:22)
    at runThing (file:///C:/Users/.../apps/langchain-playground/src/app.ts:62:3)
    at file:///C:/Users/.../apps/langchain-playground/src/app.ts:65:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
```

And if you try to use Zod's `nativeEnum` (by uncommenting the code above) it throws the same error.

**Comment by baloodevil** [comment]
This was an issue with version 0.0.55, but is working in 0.0.59.  Closing the issue.
