### ISSUE TITLE
Chroma use getOrCreateCollection method

### ISSUE THREAD

**Issue by nfcampos** [hwchase17/langchainjs#948]

**Comment by l4b4r4b4b4** [comment]
When trying to retrieve an existing collection from chromaDB with langchain.js integration. For some reason, it tries to create a new one when I do that, and raises an error that the collection already exists. Anyone got some pointers on how to do that?

**Comment by nfcampos** [comment]
I've opened a pr for this

**Comment by l4b4r4b4b4** [comment]
Following up: the method successfully returns the existing vector store. Still it tries to create it as well and raises the error mentioned. Don't understand why it should do that in the first place. For context here is are the logs on ChromaDB
```
chromadb-1  | 2023-04-23T11:47:27.680435741Z 2023-04-23 11:47:27 ERROR    chromadb.server.fastapi Collection with name energizer already exists
chromadb-1  | 2023-04-23T11:47:27.680460718Z Traceback (most recent call last):
chromadb-1  | 2023-04-23T11:47:27.680465497Z   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
chromadb-1  | 2023-04-23T11:47:27.680469444Z     return self.receive_nowait()
chromadb-1  | 2023-04-23T11:47:27.680472911Z   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
chromadb-1  | 2023-04-23T11:47:27.680476698Z     raise WouldBlock
chromadb-1  | 2023-04-23T11:47:27.680480335Z anyio.WouldBlock
chromadb-1  | 2023-04-23T11:47:27.680484142Z 
chromadb-1  | 2023-04-23T11:47:27.680487428Z During handling of the above exception, another exception occurred:
chromadb-1  | 2023-04-23T11:47:27.680491055Z 
chromadb-1  | 2023-04-23T11:47:27.680494301Z Traceback (most recent call last):
chromadb-1  | 2023-04-23T11:47:27.680497647Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
chromadb-1  | 2023-04-23T11:47:27.680501314Z     message = await recv_stream.receive()
chromadb-1  | 2023-04-23T11:47:27.680504751Z   File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
chromadb-1  | 2023-04-23T11:47:27.680508307Z     raise EndOfStream
chromadb-1  | 2023-04-23T11:47:27.680511623Z anyio.EndOfStream
chromadb-1  | 2023-04-23T11:47:27.680515070Z 
chromadb-1  | 2023-04-23T11:47:27.680518456Z During handling of the above exception, another exception occurred:
chromadb-1  | 2023-04-23T11:47:27.680522273Z 
chromadb-1  | 2023-04-23T11:47:27.680525850Z Traceback (most recent call last):
chromadb-1  | 2023-04-23T11:47:27.680529287Z   File "/chroma/./chromadb/server/fastapi/__init__.py", line 47, in catch_exceptions_middleware
chromadb-1  | 2023-04-23T11:47:27.680533004Z     return await call_next(request)
chromadb-1  | 2023-04-23T11:47:27.680544976Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
chromadb-1  | 2023-04-23T11:47:27.680548803Z     raise app_exc
chromadb-1  | 2023-04-23T11:47:27.680552079Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
chromadb-1  | 2023-04-23T11:47:27.680555776Z     await self.app(scope, request.receive, send_stream.send)
chromadb-1  | 2023-04-23T11:47:27.680559263Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
chromadb-1  | 2023-04-23T11:47:27.680562840Z     raise exc
chromadb-1  | 2023-04-23T11:47:27.680566126Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
chromadb-1  | 2023-04-23T11:47:27.680569692Z     await self.app(scope, receive, sender)
chromadb-1  | 2023-04-23T11:47:27.680573199Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
chromadb-1  | 2023-04-23T11:47:27.680576746Z     raise e
chromadb-1  | 2023-04-23T11:47:27.680579962Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
chromadb-1  | 2023-04-23T11:47:27.680583488Z     await self.app(scope, receive, send)
chromadb-1  | 2023-04-23T11:47:27.680588438Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
chromadb-1  | 2023-04-23T11:47:27.680593607Z     await route.handle(scope, receive, send)
chromadb-1  | 2023-04-23T11:47:27.680599308Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
chromadb-1  | 2023-04-23T11:47:27.680604418Z     await self.app(scope, receive, send)
chromadb-1  | 2023-04-23T11:47:27.680608846Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
chromadb-1  | 2023-04-23T11:47:27.680612593Z     response = await func(request)
chromadb-1  | 2023-04-23T11:47:27.680615919Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
chromadb-1  | 2023-04-23T11:47:27.680619526Z     raw_response = await run_endpoint_function(
chromadb-1  | 2023-04-23T11:47:27.680622852Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
chromadb-1  | 2023-04-23T11:47:27.680626369Z     return await run_in_threadpool(dependant.call, **values)
chromadb-1  | 2023-04-23T11:47:27.680630937Z   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
chromadb-1  | 2023-04-23T11:47:27.680635947Z     return await anyio.to_thread.run_sync(func, *args)
chromadb-1  | 2023-04-23T11:47:27.680641156Z   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
chromadb-1  | 2023-04-23T11:47:27.680646036Z     return await get_asynclib().run_sync_in_worker_thread(
chromadb-1  | 2023-04-23T11:47:27.680651045Z   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
chromadb-1  | 2023-04-23T11:47:27.680656205Z     return await future
chromadb-1  | 2023-04-23T11:47:27.680660723Z   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
chromadb-1  | 2023-04-23T11:47:27.680671714Z     result = context.run(func, *args)
chromadb-1  | 2023-04-23T11:47:27.680676523Z   File "/chroma/./chromadb/server/fastapi/__init__.py", line 141, in create_collection
chromadb-1  | 2023-04-23T11:47:27.680681622Z     return self._api.create_collection(
chromadb-1  | 2023-04-23T11:47:27.680686572Z   File "/chroma/./chromadb/api/local.py", line 91, in create_collection
chromadb-1  | 2023-04-23T11:47:27.680691711Z     res = self._db.create_collection(name, metadata, get_or_create)
chromadb-1  | 2023-04-23T11:47:27.680696731Z   File "/chroma/./chromadb/db/clickhouse.py", line 151, in create_collection
chromadb-1  | 2023-04-23T11:47:27.680702191Z     raise ValueError(f"Collection with name {name} already exists")
chromadb-1  | 2023-04-23T11:47:27.680707741Z ValueError: Collection with name energizer already exists
chromadb-1  | 2023-04-23T11:47:27.680882760Z 2023-04-23 11:47:27 INFO     uvicorn.access  172.30.0.4:45838 - "POST /api/v1/collections HTTP/1.1" 500
chromadb-1  | 2023-04-23T11:47:28.991339213Z 2023-04-23 11:47:28 INFO     uvicorn.access  172.30.0.4:45838 - "POST /api/v1/collections/energizer/query HTTP/1.1" 500
```
